name: reply
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.6
  - numpy=1.18.1
  - scipy=1.4.1
  - pandas=0.25.3
  - plotly=4.5.0
  - python-cufflinks=0.17
  - jupyter=1.0.0
  - jupytext=1.3.4
  # linters
  - mypy
  - pylint
  - pylama
  - autopep8
